[profile.default]
src = "src"
out = "out"
libs = ["lib"] # It's good practice to keep this line for forge-std
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
sepolia = "https://1rpc.io/sepolia"
