[profile.default]
src = "src"
out = "out"
load_from_env_file = true
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    # Corrected, less specific paths for node_modules packages
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    
    # Standard path for forge-std
    'forge-std/=lib/forge-std/src/'
]


[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
sepolia = "https://1rpc.io/sepolia"
avalanche_fuji = "https://avalanche-fuji.drpc.org"
