name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    # ...
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.0
      
      - name: Install NPM Dependencies
        run: pnpm install
      
      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        id: test
