name: CI

on:
  # This section tells GitHub WHEN to run the workflow.
  push:
    # We are specifying to only run on pushes to the 'main' branch.
    branches:
      - main
  
  # This allows you to manually run the workflow from the "Actions" tab on GitHub.
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry Project Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.0
      
      - name: Install NPM Dependencies
        run: pnpm install

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        id: test
